# Generated by Django 2.2.1 on 2019-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa_watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='neighborhood_id',
            field=models.IntegerField(default=1),
        ),
    ]
