# Generated by Django 2.2.1 on 2019-05-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa_watch', '0002_neighborhood_neighborhood_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='neighborhood_id',
        ),
    ]
