# Generated by Django 2.2.1 on 2019-05-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa_watch', '0004_auto_20190530_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtaa_watch.Neighborhood'),
            preserve_default=False,
        ),
    ]
