# Generated by Django 2.2.1 on 2019-05-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa_watch', '0005_auto_20190530_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='admin',
        ),
    ]
