# Generated by Django 2.2.1 on 2019-05-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa_watch', '0008_auto_20190530_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_name',
            field=models.CharField(max_length=50),
        ),
    ]
