# Generated by Django 2.2.1 on 2019-05-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa_watch', '0011_auto_20190530_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighborhood',
        ),
    ]
